#! /bin/sh
#| -*- racket -*-
exec racket -tm "$0" -- ${1+"$@"}
|#
#lang racket

;; usage:
;; ./xobserve --file path-to-file.json 
;;
;; xor
;; 
;; ./xobserve fish = F players = P rows = R columns = C
;; for F, P, R, C and D in Naturals
;; The command line may specify these parameters in any order, abd every field is optional.
;; 
;; example: 
;; ./xobserve fish=5 players = 4 row = 2 columns = 9 

;; main n:natural runs a game with n AI players and one human controled player, plus one observer 

(provide main)

;; ---------------------------------------------------------------------------------------------------
(require Fish/Admin/referee)
(require Fish/Admin/game-observer)
(require Fish/Scripts/Private/report-results)
(require Fish/Scripts/Private/configure)

;; ---------------------------------------------------------------------------------------------------
(define (main . n)
  (define-values (players names make-state) (configure-game n))
  (define state0 (make-state players))
  (match-define (list rankings failures) (referee state0 #:time-out 3 #:observers (list observer)))
  (report-results names players rankings failures)
  (sleep 30))
