#! /bin/sh
#| -*- racket -*-
exec racket -tm "$0" -- ${1+"$@"}
|#
#lang racket

;; usage:
;; ./xplay --file path-to-file.json 
;;
;; xor
;; 
;; ./xplay fish = F players = P rows = R columns = C
;; for F, P, R, C and D in Naturals
;; The command line may specify these parameters in any order, abd every field is optional.
;; 
;; The number of players must be less than 4 so the script can add a human. 
;; 
;; example: 
;; ./xplay fish=5 players = 3 row = 2 columns = 9 

;; main n:natural runs a game with n AI players and one human controled player, plus one observer 

(provide main)

;; ---------------------------------------------------------------------------------------------------
(require Fish/Admin/referee)
(require Fish/Player/human)

(require Fish/Scripts/Private/report-results)
(require Fish/Scripts/Private/configure)

;; ---------------------------------------------------------------------------------------------------
(define (main . n)
  (define-values (players names make-state) (configure n))
  (unless (< (length players) 4)
    (printf "usage: ./xplay player = n .. config ..\n")
    (printf "       where n is 1, 2, or 3\n")
    (exit 1))
  (define the-human (new human%))
  (define state0  (make-state (cons the-human players)))
  (match-define (list rankings failures) (referee state0 #:time-out 20))
  (report-results names players rankings failures))

