#! /bin/sh
#| -*- racket -*-
exec racket -W error -tm "$0" -- ${1+"$@"}
|#
#lang racket

;; main p:port-number (between 10,000 and 60,000) launches a server on this port 

(provide main)

;; ---------------------------------------------------------------------------------------------------
(require Fish/Scripts/Private/run-server-client)
(require Fish/Scripts/Private/configure)

;; ---------------------------------------------------------------------------------------------------
(define (main p-str)
  (define p (configure-server (list "port = " p-str)))
  (pretty-print `[starting a server on ,p])
  (run-server p))
