#! /bin/sh
#| -*- racket -*-
exec racket -W error -tm "$0" -- ${1+"$@"}
|#
#lang racket

;; main p:port-number (between 10,000 and 60,000) launches a server on this port 

(provide main)

;; ---------------------------------------------------------------------------------------------------
(require Fish/Scripts/Private/run-server-client)

;; ---------------------------------------------------------------------------------------------------
(module+ main
  (apply main (vector->list (current-command-line-arguments))))

(define (main p-str)
  (define p (string->number p-str))
  (displayln `[starting a server on ,p])
  (run-server p))
